### ISSUE TITLE
Test for accessible pcbnew API, prompt to update kicad if needed

### ISSUE THREAD

**Issue by qu1ck** [random-builder/kicad_freerouting-plugin#2]
Defensive check is better than a stack trace in user's face.

**Comment by Andrei-Pozolotin** [comment]
sure, please link here any good patterns of defensive check in kicad plugins

**Comment by qu1ck** [comment]
I don't know if its "good" pattern but here is how I detect missing api:
https://github.com/openscopeproject/InteractiveHtmlBom/blob/master/InteractiveHtmlBom/core/ibom.py#L241

Essentially just
```python
if not hasattr(pcbnew, 'ExportSpecctraDSN'):
  # show error with clear message
  return
```
is enough

**Comment by Andrei-Pozolotin** [comment]
please review https://github.com/random-builder/kicad_freerouting-plugin/pull/3
